### ISSUE TITLE
Avoid nested KM interpolation

### ISSUE THREAD

**Issue by hfrick** [tidymodels/censored#114]
See if un-nesting 

https://github.com/tidymodels/censored/blob/main/R/party.R#L101-L102

and 

https://github.com/tidymodels/censored/blob/main/R/party.R#L259-L260

similar to #91 makes it noticeably faster.

**Comment by EmilHvitfeldt** [comment]
Even pulling out `dplyr::select()` is going to help a lot

**Comment by hfrick** [comment]
closed in #224
