### ISSUE TITLE
party models argument specification

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/censored#13]
There have been talk in multiple repositories to add `party` support (treesnip and survnip)

Where should the argument specification go with `set_model_arg()`?

cc
https://github.com/curso-r/treesnip/issues/30
https://github.com/EmilHvitfeldt/survnip/issues/6 & https://github.com/EmilHvitfeldt/survnip/issues/8

**Comment by topepo** [comment]
I started work on this for `treesnip`. It requires a wrapper function and is a little difficult due to the models being S4 objects. I'll prototype in a branch.
