### ISSUE TITLE
family for glmnet

### ISSUE THREAD

**Issue by topepo** [tidymodels/censored#182]
For the case weights branch in parsnip, there is an error with glmnet and Cox models. 

``` r
library(survival)
library(censored)
#> Loading required package: parsnip
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tidyr)

mod <- 
    proportional_hazards(penalty = 0.01) %>% 
    set_engine("glmnet", nlambda = 5) %>% 
    fit(Surv(futime, fustat) ~ age + ecog.ps + strata(rx), data = ovarian)
#> Error in glmnet::glmnet(data_obj$x, data_obj$y, family = "cox", alpha = alpha, : formal argument "family" matched by multiple actual arguments
```
<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The model definition has `family` in `protects` but the glmnet wrapper sets it internally (i.e. it is not an argument to set). Users could pass it in via the dots though. 

The case weight branch will cause an error because `family` is not an argument.

Can we either make it an argument or remove it from `protects` (recommended).

**Comment by hfrick** [comment]
@topepo I saw that you made a `case-weights` branch for censored already. It also includes this change of "unprotecting" the `family` arg. Do you want to use that code in a PR or did you want to address this differently?

Are only data arguments supposed to be protected?

**Comment by topepo** [comment]
I'll need to merge the parsnip case weights PR soon and I think that this will break censored. Should I wait until there is a PR for this issue (or any other case weight work)?

**Comment by hfrick** [comment]
yes, that'd be great, thanks - I'll get to this issue this week 👍
