### ISSUE TITLE
move  existing survival functions in parsnip over to this package

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/censored#2]

**Comment by EmilHvitfeldt** [comment]
all `surv_reg()` functionality has been moved to over to survnip.

I have commented out the registration here https://github.com/tidymodels/parsnip/pull/359/commits/2b6f06fe4fc9de1ea3de28ea2b4f3c1192777e27 to avoid registering the model twice.

How should we proceed with this move? Should we delete everything and time the releases?
I like the idea of simply setting the surv_reg() model and nothing else in parsnip and then add everything else in survnip.

**Comment by topepo** [comment]
I'm coming over to your more recent idea of having the model definitions live in `parsnip` and the engine details residing here. 

For `surv_reg()`, I'd say let's keep `survival_reg()` as the name and move that to `parsnip`. That way we can deprecate `surv_reg()` gradually.
