### ISSUE TITLE
I want to port over all models from xgbse to here

### ISSUE THREAD

**Issue by brunocarlin** [tidymodels/censored#262]
xgbse is a package from Python that uses base survival models cox and aft from xgboost and enhances them with 4 techniques

https://loft-br.github.io/xgboost-survival-embeddings/how_xgbse_works.html

XGBSEDebiasedBCE
XGBSEStackedWeibull
XGBSEKaplanNeighbors
XGBSEKaplanTree

And allows you to bootstrap any of them using

XGBSEBootstrapEstimator

I want to develop a port into censored. I have already started the port of cox and aft

Should I split my work into my package, or can I keep it here?

Do you have any tips if I should focus on integrating with stacks?

**Comment by hfrick** [comment]
Hi! :wave: 

Thanks for the issue! I'd say it makes sense to put the port to the Python package in your own R package and then we can look into using that as an engine in censored. Regarding stacks: if the models are parsnip models, then stacking with {stacks} should work out of the box.
