### ISSUE TITLE
update tests for `aorsf` version 0.1.2

### ISSUE THREAD

**Issue by bcjaeger** [tidymodels/censored#287]
Hello!

I am planning to release `aorsf` version 0.1.2 soon, and this update will provide support for both classification and regression oblique random forests. Internally, I've re-worked some of the attributes and class types of `aorsf`, which means the new version will break some of the tests in `test-rand_forest_aorsf.R`. I've prepared a pull request with minor changes to this file that will make it compatible with 0.1.2. Would it be okay if I submitted this PR for you to review?

I'd be happy to add some additional code in this PR to resolve #283 if you'd like! Just let me know.

edit: my mistake, version 0.1.2

**Comment by EmilHvitfeldt** [comment]
Hello @bcjaeger 👋 

Thanks for the heads up! The PR is highly welcomed! We are all out-of-office between Christmas and new years, but we will look at it once we are back!

**Comment by bcjaeger** [comment]
Excellent, thank you! I appreciate the reply and hope you are having a lovely time away.

**Comment by hfrick** [comment]
closed in #288
