### ISSUE TITLE
multi-predict for some prediction types

### ISSUE THREAD

**Issue by topepo** [tidymodels/censored#29]
With `glmnet` (and maybe `mboost`) we can get predictions one many values of some tuning parameters without multiple model fits. `parsnip` saves those as nested tibbles per row of `new_data`. 

This is also how we store the predictions of hazard and survival probabilities. 

We _might_ be able to  accommodate both by having a single nested for both.  For example, for `glmnet`, we would have the full grid of `penalty` and `.time` values with an additional column for the prediction.

**Comment by hfrick** [comment]
#70 covers `multi_predict()` for glmnet's Cox models for the prediction types `"survival"` and `"linear_pred"`.

**Comment by hfrick** [comment]
todo: `type = "time"` for `glmnet`

**Comment by hfrick** [comment]
possible todo: `mboost`

**Comment by hfrick** [comment]
Added the remaining prediction types of glmnet models in #282 , and am going to close this issue in favor of a new one specifically for mboost: #290
