### ISSUE TITLE
PH models and probability estimates

### ISSUE THREAD

**Issue by topepo** [tidymodels/censored#30]
There is currently some code in `aaa_survival_prop.R` to estimate survival probabilities for Cox PH models. It might be better to use `survift(coxph_object)` or `basehaz(coxph_object)` to get these since they take into account any stratification variables for that model. If that's the case, we might want to save the table produced by those functions in the model object and interpolate the step functions within each strata. Dealing with the strata is a pain, because of how `survival` encodes them, but some of that work is already done for the parametric model engine. 

Also, I don't see any canonical ways of estimating the baseline hazard so that we can get `type = "hazard"`. There as some methods that layer another model on top of the PH model results. It would be good to get community feedback on this. 

We might also consider having a `type = "cumulative hazard"` method

@dincerti

**Comment by dincerti** [comment]
I would echo max and suggest using `survfit()` to get survival predictions. It does a lot under the hood and can handle stratification, start/stop data, etc. There is also a `summary.survfit()` method can can interpolate for arbitrary time points. 

`type = "cumulative_hazard"` would be a good idea and would work for most/all models. Perhaps `type = "hazard"` could be restricted to  models where it is straightforward to compute (i.e., for parametric models)?

**Comment by topepo** [comment]
Do people ever want (instantaneous) hazard estimates for this model?

**Comment by hfrick** [comment]
update: survival probabilities for `coxph` models now use `survfit()`

leaving this open for the (instantaneous) hazard discussion

**Comment by dincerti** [comment]
I think hazards can be useful as a diagnostic (e.g., for understanding whether a parametric model seems reasonable, exploring non-proportional hazards). But I don't think they are nearly as useful as other summaries of the survival distribution, particularly in a prediction context.

**Comment by hfrick** [comment]
thanks for the feedback @dincerti !
