### ISSUE TITLE
missing values in data when getting survival probabilities with coxph()

### ISSUE THREAD

**Issue by topepo** [tidymodels/censored#40]
It looks like `na.exclude()` doesn't pad the results of `survfit.coxph()` with NA values (in the resulting matrix). This happens with or without strata. 

``` r
library(survival)
# survival    * 3.2-7      2020-09-28 [1] CRAN (R 4.0.3) 

mod <- coxph(Surv(time, status) ~ age + ph.ecog, data = lung,
             na.action = na.exclude)
```

``` r

# lung$ph.ecog[14] is NA
new_x <- lung[1:15, c("ph.ecog", "age")]

length(predict(mod, new_x, na.action = na.exclude))
#> [1] 15
```

``` r

surv_estimates <- survfit(mod, newdata = new_x,
                          na.action = na.exclude)
dim(surv_estimates$surv)
#> [1] 185  14
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9000)</sup>

The `survival` maintainer will not fix this 

>  For operations that return a value per subject, then na.action plays a role. But that is not what a survival curve is.

> What is the compeling use case that would justify months of work? You would need to start by finding all the downstream routines that would be affected, map out what they should do, then whether they now need an na.omit option. document it, and test it. The use case would need to be very strong.

**Comment by EmilHvitfeldt** [comment]
Is this related to this behavior?

``` r
library(censored)
library(survival)

cox_mod <-
  proportional_hazards() %>%
  set_engine("survival") %>%
  fit(Surv(time, status) ~ age + ph.ecog, data = lung)

predict(cox_mod, type = "survival", new_data = lung[12, ], time = c(100, 200))
#> # A tibble: 1 x 1
#>   .pred           
#>   <list>          
#> 1 <tibble [2 × 2]>

predict(cox_mod, type = "survival", new_data = lung[14, ], time = c(100, 200))
#> Error in outer(fit$cumhaz, c(x2)) - fit$xbar: non-conformable arrays
```

<sup>Created on 2021-05-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by hfrick** [comment]
Yes, if one of several observations in the new data contains NA `survfit()` omits the row, if it's the only row it errors:

``` r
library(survival)

mod <- coxph(Surv(time, status) ~ age + ph.ecog, data = lung,
             na.action = na.exclude)

# lung[14, ] contains NA
survfit(mod, newdata = lung[14, ], na.action = na.exclude)
#> Error in outer(fit$cumhaz, c(x2)) - fit$xbar: non-conformable arrays

new_x <- lung[1:14, ]
surv_estimates <- survfit(mod, newdata = new_x,
                          na.action = na.exclude)
dim(surv_estimates$surv)
#> [1] 185  13
```

<sup>Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
