### ISSUE TITLE
Speed up predictions of survival probabilities for proportional hazards models?

### ISSUE THREAD

**Issue by hfrick** [tidymodels/censored#47]
this applies to the `survival` and `glmnet` engines

**Comment by EmilHvitfeldt** [comment]
It appears that at least some of the slowness comes from `interpolate_km_values`, but it seems to come mostly from error handling

reprex

```r
set.seed(1234)
x <- tibble(
  .time = cumsum(sample(1:6, 100, TRUE)),
  .pred_survival = c(1, sort(runif(99), TRUE)),
  .pred_survival_lower = NA,
  .pred_survival_upper = NA,
  .pred_hazard_cumulative = cumsum(runif(100))
)

for (i in 1:1000)
  censored:::interpolate_km_values(x, .times)
```

<img width="974" alt="Screen Shot 2021-04-27 at 8 02 36 PM" src="https://user-images.githubusercontent.com/14034784/116340229-ab3f1000-a793-11eb-927f-3b370689ebb8.png">
<img width="1049" alt="Screen Shot 2021-04-27 at 8 02 50 PM" src="https://user-images.githubusercontent.com/14034784/116340231-ac703d00-a793-11eb-84d7-d5bc18f758a9.png">
