### ISSUE TITLE
Standardize naming of internal survival_prob_*() functions

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/censored#51]
apart from `surv_prob_ctree()` and `surv_prob_cforest()` we also have `cph_survival_prob()` and `coxnet_survival_prop()`. Feels like we should standardize, how about `survival_prob_<fit class>()`? apart from  and  we also have  and . Feels like we should standardize, how about ?

_Originally posted by @hfrick in https://github.com/tidymodels/censored/pull/50#discussion_r621211105_

**Comment by topepo** [comment]
closed with 3520a29
